version: "3.8"

services:
    database:
        image: postgres
        container_name: database_register_user
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=register_user
            - POSTGRES_PASSWORD=register_user
            - POSTGRES_DB=register_user
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: app_register_user
        ports: 
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on: 
            - database
        

volumes:
    pgdata:
        driver: local